move radio button to headless architecture
Beehive-Software-Consultants/beesoft-components pull request #136
Opened 2024-07-02 20:00 UTC by thectogeneral

Hi @brandontrabon I need a review.

2024-07-06 14:38 UTC, brandontrabon requested changes
I would take a look at my current date component conversion for some ideas how this should be done.

2024-07-06 14:38 UTC, brandontrabon commented on src/components/form/radio-buttons/radio-button/radio-button.component.tsx
> +  orientation = FormGroupItemOrientation.Horizontal,
Why the switch here? Usually radio buttons are listed vertically.

2024-07-06 14:38 UTC, brandontrabon commented on src/components/form/radio-buttons/radio-button/radio-button.component.tsx
> +        {label && <HeadlessLabel label={label} className={labelStyles} />}
You can use the `Label` component here. It uses the `HeadlessLabel` internally.

2024-07-06 14:38 UTC, brandontrabon commented on src/components/form/radio-buttons/radio-button/radio-button.component.tsx
> +        ></HeadlessRadioButton>
The headless component should have a render function that is used to actually render the UI.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-button.component.tsx
> +      <HeadlessRadioItem
None of the headless components should be containing other headless components. If you want to see an example of what I'm talking about look at my branch `feature/BSC-72-headless-date`. Here you should be using the `HeadlessBase` component.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-button.component.tsx
> +  });
Headless components shouldn't include style unless its used for something like hiding an element.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-button.component.tsx
> +      {label && <HeadlessLabel label={label} />}
This shouldn't be included in the headless component.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-button.component.tsx
> +    data,
The data shouldn't be included in this component; it should be passed into the main radio button component and then looped through in the render function of this component.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-button.component.tsx
> +    className,
None of these items should be passed into this component; these are visual style properties.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-button.component.tsx
> +  const staticData = useDeepMemo(() => data, [data]);
With data gone this should be as well.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-button.component.tsx
> +  const useAnimationState = useShouldAnimate(useAnimation);
This should be only in the main radio button component.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-button.component.tsx
> +      {staticData && renderItems(staticData)}
This shouldn't be included either since we are removing the data.

2024-07-06 14:38 UTC, brandontrabon commented on src/components/form/radio-buttons/radio-button/radio-button.component.tsx
> -  const staticData = useDeepMemo(() => data, [data]);
This should stay here.

2024-07-06 14:38 UTC, brandontrabon commented on src/components/form/radio-buttons/radio-button/radio-button.component.tsx
> -  const containerStyles = cx('bc-radio-container bsc-flex bsc-flex-col bsc-gap-1', className);
This should also stay here.

2024-07-06 14:38 UTC, brandontrabon commented on src/components/form/radio-buttons/radio-button/radio-button.props.ts
> +  extends ReplacePropertyType<HeadlessRadioButtonProps, 'onChange', (value?: RadioChangeEvent) => void>,
Why was the extends changed here? OK after looking at your other changes I think I know why you think you needed to do this, but you should leave the `onChange` with the headless type in it.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/headless-radio-button.interfaces.ts
This will be fine for now...we may want to start thinking about something generic, but lets wait until we get to that point.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-button.component.tsx
> +  const renderItems = (finalData: JsonData) => <div className={radioStyles}>{finalData.map(renderRadioButton)}</div>;
This shouldn't be here either.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-item-props.tsx
> +export interface HeadlessRadioItemProps extends ComponentAnimationProps {
The `ComponentAnimationProps` shouldn't be used here since this is a headless component.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-item-props.tsx
>    labelLocation?: SelectionLabelLocation;
No style related properties should be in a headless component.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-item.component.tsx
You need to utilize the group context here, so it can tie back to the main component. Look at what I did with the checkbox component.

2024-07-06 14:38 UTC, brandontrabon commented on src/headless/components/form/radio-buttons/radio-button/headless-radio-item.component.tsx
> +    </label>
This should contain the hidden radio button element and then use the headless base component to call a render function to allow the actual UI to be created.

2024-07-08 07:25 UTC, thectogeneral commented
Thank you @brandontrabon. I will take my time to work on it this week.

2025-07-19 12:34 UTC, closed without merging